// External links removed - powered by imoogle
export const DISCORD_HANDLE = '#'
export const GITHUB_LINK = '#'
export const TWITTER_HANDLE = '#'
export const LINKEDIN_HANDLE = '#'
export const YOUTUBE_HANDLE = '#'
export const DOMAIN_URL = 'http://localhost:3000'
export const GITHUB_API_BASE = '#'
export const GITHUB_REPO_BASE = '#'
export const BASE_URL = 'http://localhost:3000'
